ProjectFBSentiments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="index"),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

accounts/urls.py
from django.urls import path
from . import views, forms

app_name = 'accounts'

urlpatterns = [
    path('login/', views.signin , name='signin'),
    path('logout/', views.signout, name='signout'),
    path('signup/', views.signup, name='signup'),
]

dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    re_path(r'^posts/(?P<page_id>[0-9_]+)/$', views.posts, name="posts"),
    re_path(r'^post/(?P<id>[0-9_]+)/$', views.post_view, name="postview"),
    path('post/analyze_post', views.analyze_post, name="analyzepost"),
    path('post/generate_csv', views.generate_csv, name="generatecsv"),
    path('search_page', views.searchpage, name="searchpage")
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Page(models.Model):
    page_id = models.IntegerField()
    page_name = models.CharField(max_length = 255)
    page_picture = models.TextField()
    page_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.page_name

# class Post(models.Model):
#     post_id = models.CharField(max_length = 255)
#     post_message = models.TextField()
#     post_picture = models.TextField()
#     post_page = models.ForeignKey(Page, on_delete=models.CASCADE)


#     def __str__(self):
#         display = self.post_message.split(' ')[0] + "..."
#         return display

# class Comment(models.Model):
#     comment_message = models.TextField()
#     comment_from = models.CharField(max_length = 255)
#     comment_id = models.CharField(max_length = 255)
#     comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)

#     def __str__(self):
#         display = self.comment_message.split(' ')[0] + "..."
#         return display

dashboard/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .sentiment_analysis import SentimentAnalysis
from .facebook_graph_api_explorer import FetchData
from .models import Page
import os
import csv

# Create your views here.

data = FetchData()
analysis = SentimentAnalysis()

@login_required
def dashboard(request):
    pages = Page.objects.filter(page_user=User.objects.filter(username=request.user)[0])
    context = {
        'user': request.user,
        'pages': pages
    }
    return render(request, 'dashboard/dashboard.html', context)


@login_required
def searchpage(request):
    if request.method == 'POST':
        page_id = request.POST.get('pageid')
        page_user = User.objects.filter(username=request.user)[0]

        if not Page.objects.filter(page_id=page_id, page_user=page_user):
            page_data = data.fetch_page_data(page_id)
            Page.objects.create(page_id=page_id, page_name=page_data['name'], page_picture=page_data['picture']['data']['url'], page_user=page_user)
        

    return posts(request, page_id)

    

@login_required
def posts(request, page_id):
   
    context = {
        'posts': data.fetch_all_posts(page_id)
    }
    return render(request, 'dashboard/posts.html', context)


@login_required
def post_view(request, id):
    post = data.fetch_one_post(id)
   
        

    context = {
        'post': post
        # 'prediction': prediction,
        # 'p_count': p_count,
        # 'n_count': n_count,
        # 'accuracy': accuracy,
    }
    
    return render(request, 'dashboard/postview.html', context)

def analyze_post(request):
    if request.is_ajax and request.method == "GET":
        comments = request.GET.getlist('comments[]')
        p_count = 0
        n_count = 0
    
        analysis.create_model()
        accuracy = str(round(analysis.get_accuracy() * 100)) + " %"
        prediction = []

        
        if len(comments) == 1:
            prediction = [[comments[0], analysis.predict_one_review(comments[0])]]

        else:
            prediction = analysis.predict_many_reviews(comments)

            for s_count in prediction:
                if s_count[1] == "Positive":
                    p_count += 1
                else:
                    n_count += 1
        return JsonResponse({
            "p_count": p_count,
            "n_count": n_count,
            "accuracy": accuracy,
            "prediction": prediction
            }, status=200)
    else:
        return JsonResponse({"error": "An error occurred"}, status=400)


def generate_csv(request):
    if request.is_ajax and request.method == "GET":
        predictions = []
        for i in range(int(request.GET['predLength'])):
            prediction = request.GET.getlist(f'prediction[{i}][]')
            predictions.append(prediction)
        
        desktop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')

        with open(desktop + '\data.csv', 'w+', newline="") as file:
            fieldnames = ['comment', 'prediction']

            writer = csv.DictWriter(file, fieldnames=fieldnames)

            writer.writeheader()
            for pred in predictions:
                writer.writerow({'comment': pred[0], 'prediction': pred[1]})

            return JsonResponse({
                "success": "Successfully generataed the csv file"
            }, status=200)
    else:
        return JsonResponse({"error": "An error occurred"}, status=400)


    

dashboard/templates/dashboard/dashboard.html
{% extends 'layout.html' %}
{% load static %}


{% block title %}
    Dashboard | {{user}}
{% endblock %}
    


{% block dnav %}
    <nav class="navbar navbar-expand-lg dark-nav">
        <div class="dashboard-nav-left">
            <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_footer_img.png' %}" alt="logo" class="logo-style"></a>
            <button class="btn btn-icon sidebar-toggler" id="btn-sidebar-toggler"><i class="fas fa-bars"></i></button>
        </div>
        <div class="dashboard-nav-right">
            <p class="dashboard-nav-text">Dashboard</p>
            <a href="{% url 'accounts:signout' %}" class="btn btn-full signout-btn">SIGN OUT</a>
        </div>
    </nav>
{% endblock %}


{% block dcontent %}
    <div class="dashboard-content-wrapper">
        <div class="sidebar-wrapper" id="sidebar">
           {% include 'dashboard/sidebar.html' %}
        </div>
        <div class="action-area-wrapper" id="action-area">
            <h4 class="text-center d-welcome-text">Hi there {{user}}! Welcome to your dashboard.</h4>
            <div class="search-wrapper">
                <form method="POST" action="{% url 'dashboard:searchpage' %}" name="search">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="pageid" placeholder="Enter page id to fetch its content.">
                        <div class="input-group-append">
                        <button class="btn btn-full" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
           
            <div class="content-wrapper">
                <h5 class="text-center"><b>Your Pages</b></h5>
                
                {% if pages %}
                    <div class="row">
                        {% for page in pages %}
                        <div class="col-4">
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top card-img" src="{{page.page_picture}}" alt="{{page.page_name}}">
                                <div class="card-body">
                                    <h5 class="card-title">{{page.page_name}}</h5>
                                    <a href="{% url 'dashboard:posts' page_id=page.page_id %}" class="btn btn-full">See Posts</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                {% else %}
                    <h6 class="text-center">You currently donot searched for any pages, enter your page id in the search bar to get started</h6>
                {% endif %}
                
            </div>

            
            
        </div>
    </div>
{% endblock %}
    
    

{% block dfooter %}
    {% include 'dashboard/dfooter.html' %}
{% endblock %}

dashboard/templates/dashboard/dfooter.html
{% load static %}

<footer class="dashboard-footer">
    <div class="container">
        <div class="footer-logo">
            <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_footer_img.png' %}" alt="footer-logo" class="logo-style"></a>
        </div>
    
        <div>
            <p class="d-footer-text text-center">&copy; All rights reserved by Facebook Sentiments 2020</p>
        </div>
    </div>
</footer>

dashboard/templates/dashboard/posts.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    Dashboard | {{user}}
{% endblock %}
    

{% block dnav %}
    <nav class="navbar navbar-expand-lg dark-nav">
        <div class="dashboard-nav-left">
            <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_footer_img.png' %}" alt="logo" class="logo-style"></a>
            <button class="btn btn-icon sidebar-toggler" id="btn-sidebar-toggler"><i class="fas fa-bars"></i></button>
        </div>
        <div class="dashboard-nav-right">
            <p class="dashboard-nav-text">Dashboard | Posts</p>
            <a href="{% url 'accounts:signout' %}" class="btn btn-full signout-btn">SIGN OUT</a>
        </div>
    </nav>
{% endblock %}

{% block dcontent %}
   <div class="dashboard-content-wrapper">
        <div class="sidebar-wrapper" id="sidebar">
            {% include 'dashboard/sidebar.html' %}
        </div>
        <div class="action-area-wrapper" id="action-area">
           
            <div class="content-wrapper">
                
                {% if posts %}
                    <table class="table table-stripped">
                        <thead>
                            <tr>
                                <th>Post Image</th>
                                <th>Post Message</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>    
                            {% for post in posts %}
                                <tr>
                                    <td>
                                        {% if post.picture %}
                                            <img class="thumbnail post-img" src="{{post.picture}}" alt="post img">
                                        {% else %}
                                            <img class="thumbnail post-img" src="{% static 'ProjectFBSentiments/images/noimage.jpg' %}" alt="post img">
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if post.message %}
                                            <h6><b>{{post.message}}</b></h6>                                            
                                        {% else %}
                                            <h6><b>This post has no message!</b></h6>
                                        {% endif %}
                                            

                                    </td>
                                    <td>
                                        <a href="{% url 'dashboard:postview' id=post.id %}" class="link-style">View Post <i class="fas fa-arrow-right"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}  
                        </tbody>
                    </table>
                {% else %}
                    <div class="alert alert-danger alert-custom" role="alert">
                        An error occured while fetching the posts!
                    </div>
                {% endif %}
                    
            </div> 
        </div>
    </div>
{% endblock %}



{% block dfooter %}
    {% include 'dashboard/dfooter.html' %}
{% endblock %}
    

    

dashboard/templates/dashboard/postview.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    Dashboard | {{user}}
{% endblock %}
    


{% block dnav %}
    <nav class="navbar navbar-expand-lg dark-nav">
        <div class="dashboard-nav-left">
            <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_footer_img.png' %}" alt="logo" class="logo-style"></a>
            <button class="btn btn-icon sidebar-toggler" id="btn-sidebar-toggler"><i class="fas fa-bars"></i></button>
        </div>
        <div class="dashboard-nav-right">
            <p class="dashboard-nav-text">Dashboard | Post View</p>
            <a href="{% url 'accounts:signout' %}" class="btn btn-full signout-btn">SIGN OUT</a>
        </div>
    </nav>
{% endblock %}


{% block dcontent %}
    <div class="dashboard-content-wrapper">
        <div class="sidebar-wrapper" id="sidebar">
           {% include 'dashboard/sidebar.html' %}
        </div>
        <div class="action-area-wrapper" id="action-area">

            <div class="content-wrapper">
                <div class="postview-left-wrapper">
                    {% if post.picture %}
                    <img class="postview-post-img" src="{{ post.picture }}" alt="post view img">
                    {% else %}
                        <img class="postview-post-img" src="{% static 'ProjectFBSentiments/images/noimage.jpg' %}" alt="post view img">
                    {% endif %}
                    
                    {% if post.message %}
                        <h3 class="postview-post-msg">{{post.message}}</h3>
                    {% else %}
                        <h3 class="postview-post-msg">No message!</h3>
                    {% endif %}


                    
                    {% if post.comments %}
                        <button class="btn btn-full" id="analyze-post">Analyze Post</button>    
                    {% endif %}
                        
                    
                </div>
                <div class="postview-right-wrapper">
                    <h4 class="postview-cmnt-head">Comments</h4>
                    <hr>
                    
                    {% if post.comments %}
                        
                        {% for comment in post.comments.data %}
                            <p class="postview-post-cmnt cmnt-text">{{comment.message}}</p>
                        {% endfor %}
                            
                    {% else %}
                        <p>No comments!</p>
                    {% endif %}
                        
                </div>
                
                <div class="results">
                    <div class="loading-wrapper">
                        <div class="loading">
                            <h4 class="loading-text">Generating results</h4> &nbsp;&nbsp;
                            <span class="loader"><span class="loader-inner"></span></span> &nbsp;&nbsp;
                            <span class="loader"><span class="loader-inner"></span></span> &nbsp;&nbsp;
                            <span class="loader"><span class="loader-inner"></span></span>
                        </div>
                    </div>
                    <p class="accuracy"></p>
                    <select class="form-control-sm select-graph" name="selectgraph" id="selectgraph">
                        <option value="bar" selected>Bar Graph</option>
                        <option value="pie">Pie Chart</option>
                    </select>
                    <canvas id="barGraph" class="bar-graph" width="50%" height="15"></canvas>
                    <canvas id="pieChart" class="pie-chart" width="50%" height="15"></canvas>
                    <div class="csv-btn-wrapper">
                        <button type="button" class="btn btn-full btn-csv" id="generate-csv">Generate CSV file</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    
    

{% block dfooter %}
    {% include 'dashboard/dfooter.html' %}
{% endblock %}



{% block customscripts %}
<script type="text/javascript">
    // AJAX Calls
    $(document).ready(function(){

        var p_count = 0;
        var n_count = 0;
        var prediction = null;
        var accuracy = 0;

       

        function barGraph(){
            // Set new default font family and font color to mimic Bootstrap's default styling
            Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
            Chart.defaults.global.defaultFontColor = '#292b2c';

            // Bar Chart Example
            var ctx = $("#barGraph");
            var myBarChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ["Positive Reviews", "Negative Reviews"],
                    datasets: [{
                        label: 'Reviews',
                        backgroundColor: ["#0be881", "#ff5e57"],
                        borderColor: ["#05c46b", "#ff3f34"],
                        borderWidth: 2,
                        data: [
                            p_count,
                            n_count
                        ]
                    }]
                },
                options: {
                    scales: {
                        xAxes: [{
                            gridLines: {
                            display: false
                            },
                            ticks: {
                            maxTicksLimit: 2
                            }
                        }],
                        yAxes: [{
                            ticks: {
                            min: 0,
                            max: Math.max(n_count, p_count),
                            maxTicksLimit: 5
                            },
                            gridLines: {
                            display: true
                            }
                        }]
                    },
                    responsive: true,
                    legend: {
                        display: false
                    },
                    title: {
                        display: true,
                        text: 'Reviews Classification Chart'
                    }
                }
            });
        }

        function pieChart(){
            var config = {
                type: 'pie',
                data: {
                    datasets: [{
                        data: [
                            p_count,
                            n_count
                        ],
                        backgroundColor: [
                            "#0be881",
                            "#ff5e57"
                        ]
                    }],
                    labels: [
                        "Positive",
                        "Negative"
                    ]
                },
                options: {
                    responsive: true,
                    title: {
                        display: true,
                        text: 'Reviews Classification Chart'
                    }
                }
            };

            
            var ctx = $("#pieChart");
            window.myPie = new Chart(ctx, config);
        }

        $('#analyze-post').on('click', function(e){
            e.preventDefault();
            $(".loading-wrapper").css("display", "block");
            let comments = [];
            $('.cmnt-text').each(function(){
                comments.push($(this).text());
            });
            $.ajax({
                type: 'GET',
                url: "{% url 'dashboard:analyzepost' %}",
                data: {
                    "comments":comments
                },
                success: function(response){
                    $(".loading-wrapper").css("display", "none");
                    p_count = response.p_count;
                    n_count = response.n_count;
                    accuracy = response.accuracy;
                    prediction = response.prediction;

                    $("#selectgraph").css("display", "block");
                    $(".accuracy").text("Accuracy of model : " + accuracy);
                    $(".btn-csv").css("display", "block");

                    barGraph();
                    $(".btn-csv").css("display", "block");
                },
                error: function(response){
                    alert(response['error']);
                }
            });
        });

        $("#generate-csv").on("click", function(e){
            e.preventDefault();
            var predLength = prediction.length;
            $.ajax({
                type: 'GET',
                url: "{% url 'dashboard:generatecsv' %}",
                data: {
                    "prediction":prediction,
                    "predLength":predLength
                },
                success: function(response){
                    alert("File successfully created at your dasktop");
                    
                },
                error: function(response){
                    alert(response['error']);
                }
            });
        });


        $("#selectgraph").on("change", function(){
            var selectedoption = $("#selectgraph option:selected").val();

            if(selectedoption == "pie"){
                $("#barGraph").css("display", "none");
                $("#pieChart").css("display", "block");
                pieChart();

            }else{
                $("#pieChart").css("display", "none");
                $("#barGraph").css("display", "block");
                barGraph();
            }
        });
    });
</script>
{% endblock %}
    

dashboard/templates/dashboard/sidebar.html
<ul class="nav flex-column sidebar">
    <li class="nav-item link-wrapper">
        <a class="sidebar-link" href="{% url 'dashboard:dashboard' %}"><i class="fa fa-tachometer"></i> Dashboard</a>
    </li>
</ul>