ProjectFBSentiments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="index"),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

accounts/urls.py
from django.urls import path
from . import views, forms

app_name = 'accounts'

urlpatterns = [
    path('login/', views.signin , name='signin'),
    path('logout/', views.signout, name='signout'),
    path('signup/', views.signup, name='signup'),
]

dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    re_path(r'^posts/(?P<page_id>[0-9_]+)/$', views.posts, name="posts"),
    re_path(r'^post/(?P<id>[0-9_]+)/$', views.post_view, name="postview"),
    path('post/analyze_post', views.analyze_post, name="analyzepost"),
    path('post/generate_csv', views.generate_csv, name="generatecsv"),
    path('search_page', views.searchpage, name="searchpage")
]

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    Facebook Sentiments
{% endblock %}
    

{% block header %}
    <header>
        <nav class="navbar navbar-expand-lg fixed-top">
            <div class="container">
                <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_img.png' %}" alt="logo" class="logo-style"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars icon-style"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-link nav-link-style js--scroll-to-features" href="#">Features</a>
                        <a class="nav-link nav-link-style" href="#">Contact</a>
                        <div class="dropdown">
                            <a class="nav-link nav-link-style dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Follow Us
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop-link-style" href="#"><i class="fab fa-facebook-square"></i> Facebook</a>
                                <a class="dropdown-item drop-link-style" href="#"><i class="fab fa-twitter"></i> Twitter</a>
                            </div>
                        </div>
                    </div>
                    <div class="navbar-nav my-2 my-lg-0">
                        
                        {% if user.is_authenticated %}
                            <a href="{% url 'dashboard:dashboard' %}" class="nav-link btn btn-full">Dashboard</a>  

                        {% else %}
                            <a href="{% url 'accounts:signin' %}" class="nav-link link-style nav-link-special">SIGN IN</a>
                            <a href="{% url 'accounts:signup' %}" class="nav-link btn btn-full">SIGN UP FREE</a>  
                        {% endif %}
                            
                               
                    </div>
                </div>
            </div>
        </nav>
        
        <div class="hero">
            <div class="container"> 
                <div class="hero-text-box">
                    <h1 id="js--hero-text">Know what people are saying about your products.</h1>
                </div>       
                <div class="btn-center">
                    <a href="{% url 'accounts:signup' %}" class="btn btn-full hero-btn hero-btn-full">SIGN UP FREE</a>
                    <button type="button" class="btn btn-ghost btn-sm js--scroll-to-features">SHOW ME MORE</button>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
    

{% block content %}
    <div class="content">
        <section class="features" id="js--features">
            <div class="container">
                <h2>Analyze your brand reputation</h2>
                <div class="row">
                    <div class="col-md-4 features-duo-chunk">
                        <div class="features-chunk">
                            <h4>Automated Sentiment Analysis</h4>
                            <p>Perform sentiment analysis on user reviews about your product and improve your products.</p>
                        </div>
                        <div class="features-chunk">
                            <h4>Get to know your customer</h4>
                            <p>Learn what people like and dislike about your products to ensure customer satisfaction.</p>
                        </div>
                    </div>
                    <div class="col-md-8 features-img">
                        <div class="positive">
                            <p class="positive-review-example">I bought this cell phone last week. <span>Excellent</span> performance, <span>excellent</span> battery life and <span>impressive</span> camera. Definately worth buying!!</p>
                        </div>
                        <div class="negative">
                            <p class="negative-review-example">This device has soo many <span>issues</span> like battery draining <span>issue</span>, slow charging <span>issue</span>. <span>Not a staisfying</span> experience at all!!</p>
                        </div>
                    </div>
                </div>
                <div class="row features-graph-wrapper" id="js--features-graph">
                    <div class="col-md-4 features-duo-chunk">
                        <div class="features-chunk">
                            <h4>Generate beautiful graphs</h4>
                            <p>View the results generated by machine learning algorithm in beautiful graphical representation.</p>
                        </div>
                        <div class="features-chunk">
                            <h4>Choose your graph</h4>
                            <p>Choose from various options and generate graph of your choice.</p>
                        </div>
                    </div>
                    <div class="col-md-8 features-graph-alignment">
                        <img class="features-graph-style" src="{% static 'ProjectFBSentiments/images/features_graph.png' %}" alt="features-graph">
                    </div>
                </div>
                <div class="row features-report-wrapper" id="js--features-report">
                    <div class="col-md-6  features-duo-chunk">
                        <div class="features-chunk">
                            <h4>Download PDF reports</h4>
                            <p>Download the graphs in the form of pdf reports and use them in presentations.</p>
                        </div>
                        <div class="features-chunk">
                            <h4>Save the extracted data</h4>
                            <p>Save the data fetched from facebook in CSV files.</p>
                        </div>
                    </div>
                    <div class="col-md-6 features-report-alignment">
                        <img class="features-report-style" src="{% static 'ProjectFBSentiments/images/features_report.png' %}" alt="features-report">
                    </div>
                </div>
            </div>
        </section>
        <section class="how-it-works">
            <div class="container">
                <h2 class="heading-style">How it works &mdash; Simple as 1, 2, 3</h2>
                <div class="works-steps-wrapper">
                    <div class="works-steps">
                        <div class="step">
                            <div>1</div>
                            <p>Fetch the required posts and comments from facebook pages.</p>
                        </div>
                        <div class="step">
                            <div>2</div>
                            <p>Perform sentiment analysis of the fetched data.</p>
                        </div>
                        <div class="step">
                            <div>3</div>
                            <p>View the results of machine learning algorithm in a beautiful graphical form.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="easy-get-started">
            <div class="container">
                <div class="row easy-get-started-wrapper">
                    <div class="col-md-6 align-v-center">
                        <h3 class="easy-get-started-text-style">It's easy to get started</h3>
                    </div>
                    <div class="col-md-6 align-v-center">
                        <a href="{% url 'accounts:signup' %}" class="btn easy-get-started-btn-style">SIGN UP FREE</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}



{% block footer %}
    <footer>
        <div class="container">
            <div class="row footer-navs">
                <div class="col-lg-3 col-md-4 col-sm-6 content-center">
                    <a href="{% url 'index' %}"><img src="{% static 'ProjectFBSentiments/images/Logo_footer_img.png' %}" alt="footer-logo" class="logo-style"></a>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 content-center">
                    <div class="footer-nav">
                        <h5 class="footer-heading">Contact</h5>
                        <p class="footer-text"><i class="fas fa-envelope"></i> &nbsp; FBShelp@gmail.com</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 content-center">
                    <div class="footer-nav">
                        <h5 class="footer-heading">Features</h5>
                        <nav class="nav flex-column">
                            <a class="footer-links" href="#">Sentiment Analysis</a>
                            <a class="footer-links" href="#">Generate Graphs</a>
                            <a class="footer-links" href="#">Save PDF and CSV</a>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 content-center">
                    <div class="footer-nav">
                        <h5 class="footer-heading">Follow Us</h5>
                        <nav class="nav flex-column">
                            <a class="footer-links" href="#"><i class="fab fa-facebook-square"></i> &nbsp; Facebook</a>
                            <a class="footer-links" href="#"><i class="fab fa-twitter"></i> &nbsp; Twitter</a>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="copy-text">
                <p class="footer-text text-center">&copy; All rights reserved by Facebook Sentiments 2020</p>
            </div>
        </div>
    </footer>
{% endblock %}
    
    

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'ProjectFBSentiments/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ProjectFBSentiments/css/queries.css' %}">
    <link rel="stylesheet" href="{% static 'ProjectFBSentiments/css/animate.css' %}">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">


    
    <title>
        {% block title %}
            
        {% endblock %}
    </title>
        
</head>
<body>
    
    {% block header %}
        
    {% endblock %}


    
    {% block content %}
        
    {% endblock %}
    

    
    {% block footer %}
        
    {% endblock %}


     
    {% block dnav %}
        
    {% endblock %}

    
    {% block dcontent %}
        
    {% endblock %}
    
    {% block dfooter %}
        
    {% endblock %}
        
        
    
    
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/706334cc5a.js" crossorigin="anonymous"></script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Chart JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>

    <!-- Waypoint -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.5/waypoints.min.js"></script>

    <!-- Custom JS -->
    <script src="{% static 'ProjectFBSentiments/js/script.js' %}"></script>
    <script src="{% static 'ProjectFBSentiments/js/dashboard_script.js' %}"></script>
    <script src="{% static 'ProjectFBSentiments/js/charts.js' %}"></script>
    <script src="{% static 'ProjectFBSentiments/js/authentication_script.js' %}"></script>

    
    {% block customscripts %}
    {% endblock %}
        
</body>
</html>